kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: emottak-kafka-manager
  namespace: team-emottak
  labels:
    team: team-emottak
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  ingresses:
    - https://emottak-kafka-manager.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 1  # 1 instance is required since in-memory session management is used
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure: # Required
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: b2da08e5-92e6-4731-948c-08892dcca2c9 # Required for authorization
  kafka: # Optional. Required for Aiven
    pool: nav-dev
  #  vault: # Optional. Required for on-prem (the env variables SERVICE_USER_NAME, SERVICE_USER_PASSWORD can also be used)
  #    enabled: true
  #    paths:
  #      - kvPath: /serviceuser/data/<dev/srvemottak-kafka-manager    # ikke opprettet
  #        mountPath: /var/run/secrets/nais.io/service_user
  env:
    - name: APP_CONFIG_JSON # Required
      value: >
        {
          "topics": [
            {
              "name": "team-emottak.smtp.in.ebxml.payload",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "team-emottak.smtp.in.ebxml.signal",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "team-emottak.smtp.out.ebxml.signal",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "team-emottak.smtp.out.ebxml.payload",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "team-emottak.ebxml.retry",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "team-emottak.event.log",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "team-emottak.common.topic.for.development",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "team-emottak.ebms.message.details",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            }
          ]
        }
